VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes


# QMK_SETTINGS = yes

# TAP_DANCE_ENABLE = yes
# COMBO_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
# MAGIC_ENABLE = yes
# GRAVE_ESC_ENABLE = yes

# OLED_ENABLE = yes
